# permissions for end users to edit jenkinsjobexecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-jenkins-jobexec-operator
    app.kubernetes.io/managed-by: kustomize
  name: jenkinsjobexec-editor-role
rules:
- apiGroups:
  - jenkins.operatortest.io
  resources:
  - jenkinsjobexecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkins.operatortest.io
  resources:
  - jenkinsjobexecs/status
  verbs:
  - get
