---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jenkins.operatortest.io
  resources:
  - jenkinsjobexecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkins.operatortest.io
  resources:
  - jenkinsjobexecs/finalizers
  verbs:
  - update
- apiGroups:
  - jenkins.operatortest.io
  resources:
  - jenkinsjobexecs/status
  verbs:
  - get
  - patch
  - update
