apiVersion: jenkins.operatortest.io/v1
kind: JenkinsJobExec
metadata:
  labels:
    app.kubernetes.io/name: sample-jenkins-jobexec-operator
    app.kubernetes.io/managed-by: kustomize
  name: jenkinsjobexec-sample
spec:
  jobname: test_job
  parameters: {}
  secretRef:
    name: my-secret
    #namespace: default 
  configMapRef:
    name: my-configmap
    #namespace: default 

