apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  username: cmFqaXY=  # base64 encoded value of 'username'
  token: MTE4ODQ0NjI5NzNmNmY3Y2ZlMzRiODg5Mjc2MTJjNGY1OA== 
